---
server:
  port: ${PORT:8080}

spring:
  application:
    name: couchbase

  couchbase:
    bucket:
      name: default
      password:
    bootstrap-hosts: 127.0.0.1
  data:
    couchbase:
      auto-index: false
      consistency: read_your_own_writes

